version: "3.3"

services:
  mongodb:
    image: mongo
    container_name: springboot-mongo
    ports:
      - 27017:27017
    volumes:
      - ./data/springboot-mongo-data:/data/db
      - ./data/springboot-mongo-bkp:/data/bkp
    restart: always

  adtech-install-service:
    build: ./adtech-install-service
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

  adtech-query-service:
    build: ./adtech-query-service
    ports:
      - "8081:8081"
    depends_on:
      - mongodb




